language: python
python:
  - "2.7"
  - "3.6"
# command to install dependencies
install:
  - pip install --upgrade pip
  - pip install .
  - pip install .[testing]
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install python-coveralls
# command to run tests
script: 
  - py.test src --cov=src
after_success:
  - coveralls
